### ISSUE TITLE
nicht für 24v Betrieb sutable

### ISSUE THREAD

**Issue by ellensp** [GermanRepRap/Ramps-1.4.2#1]
Coverted mit Google Translate, so aplogies für schlechtes Deutsch.

Wenn Sie die Pololu Kondensatoren 35volt aktualisieren, würde Ihre Bord bereit 24Volt werden.
So dass es noch besser :)

Auch, warum hast du das nicht auf die reprap Wiki hinzufügen?

**Comment by burdickjp** [comment]
I would also appreciate capacitors to allow 24V. I am having to replace mine and it's difficult to solder down in between the tall headers.
